name: Build
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "date=$(date --iso-8601=second)" >> $GITHUB_ENV

      - name: Get latest version
        id: version
        run: echo "version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        id: docker
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            glacion/kubectl:latest
            glacion/kubectl:${{ steps.version.outputs.version }}
          build-args: |
            version=${{ steps.version.outputs.version }}
            build_date=${{ steps.date.outputs.date }}
            revision=$GITHUB_SHA

      - name: Print digest
        run: echo "${{ steps.docker.outputs.digest }}"
