name: build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of kubectl'
        required: true

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --iso-8601=second)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        id: docker
        with:
          push: true
          tags: |
            glacion/kubectl:${{ github.event.inputs.version }}
          build-args: |
            version=${{ github.event.inputs.version }}
            build_date=${{ steps.date.outputs.date }}
