name: documentation
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/documentation.yaml'
jobs:
  documentation:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
