name: periodical
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'

      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            $HOME/.poetry
            watcher/.venv
          key: python

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: '1.1.4'

      - name: Get Dependencies
        env: 
          POETRY_VIRTUALENVS_IN_PROJECT: "true"
        working-directory: watcher
        run: poetry install --no-dev
        
      - name: Dispatch Events
        working-directory: watcher
        run: .venv/bin/python main.py

